### PR TITLE
Feature/reduce php notices

### PR DESCRIPTION
**Pull request by Trainmaster**
This should fix some log entries of type `PHP Notice: Undefined index`.

### CODE REVIEW

**Comment by kermie** [comment]
Hey @Trainmaster,
thanks for this Pull Request the boys want to merge. We just miss your signed OCA which is policy:
https://github.com/OXID-eSales/oxideshop_ce/blob/b-dev-ce/CONTRIBUTING.md
Cheers!

**Comment by Trainmaster** [comment]
@kermie See #70, isn't it valid anymore?

**Comment by kermie** [comment]
> See #70, isn't it valid anymore?

Unfortunately, not. We automated the system some time ago from manual paperwork to CLAhub which made it necessary to request a new subscription. At this point we sent around an information to all CLA signers - maybe you have just overseen it? Anyways, CLAhub doesn't seem to work correctly any longer: although all checks seem to have passed here, I cannot find your Github name in the list. Need to find another alternative...

**Comment by kermie** [comment]
Good news @Trainmaster: Just switched the service from CLAhub to CLAassistant and could subsequently add all (old and CLAhub) CLA subscriptions. In your case it looks like you used two different accounts, @Trainmaster and @Frank Liepert for your commits.

**Comment by Trainmaster** [comment]
@kermie Fixed it, now everything should be fine.

**Comment by Shiftas** [comment]
Hi, could you rebase this branch so we could accept this pull request?

**Comment by Trainmaster** [comment]
@Shiftas Done. Due rebasing conflicts I did a new commit. So please review it again.

**Pull request merged**
