### PR TITLE
created new abstract class Crypt

### PR DESCRIPTION
**Pull request by alfredbez**

### CODE REVIEW

**Comment by alfredbez** [comment]
https://github.com/OXID-eSales/oxideshop_ce/blob/5a305e19330cc977f72db63a3e64e473a82b985b/source/Core/Utils.php#L120-136

**Comment by keywan-ghadami-oxid** [comment]
but that's not used is it? https://github.com/OXID-eSales/oxideshop_ce/search?utf8=%E2%9C%93&q=strRem

**Comment by alfredbez** [comment]
Ok lets remove it then

**Comment by robertblank** [comment]
So would you like to suggest to deprecate the classes Encryptor and Decryptor instead?
You probably would like to adapt or close this PR then.

**Comment by alfredbez** [comment]
I create another PR later

**Pull request closed without merging**
