### PR TITLE
Update oxarticle.php

### PR DESCRIPTION
**Pull request by TigerLeon**
The performance-setting bl_perfLoadAttributes has no functionality at the moment. This change should give it a sence.

### CODE REVIEW

**Comment by kermie** [comment]
OCA is signed, although not checked here automatically.

**Comment by leofonic** [comment]
getAttributes isn't executed automatically, so switching it off has no benefit. Why not remove this setting?

**Comment by keywan-ghadami-oxid** [comment]
i am wondering if the default value for bl_perfLoadAttributes is false and so this change would break the functionality in existing shops.

**Comment by MantasVaitkunas** [comment]
Hi @TigerLeon,
have a look at the tests failing: https://travis-ci.org/OXID-eSales/oxideshop_ce/jobs/84253629#L726. Apparently, your suggestion doesn't pull out any variants in case they're needed. To be honest: I would rather go for @leofonic 's proposal - remove what is not needed any more (as there were getters introduced ages ago for this behavior.

**Comment by Shiftas** [comment]
Removed this Performance option from shop. https://github.com/OXID-eSales/oxideshop_ce/commit/00e9b3438c1821ad5583f94a5ef8abe80d8c5717

**Comment by TigerLeon** [comment]
Thank you. Also needed in EE:
https://bugs.oxid-esales.com/view.php?id=6239

**Pull request closed without merging**
