### PR TITLE
Added possibility to add a custom offline-page

### PR DESCRIPTION
**Pull request by JaroslavHerber**
It should be possible to overwrite the static 500-status offline.html
This standard-page and status-code isn't good for SEO at all.

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @JaroslavHerber! Thanks for the improvement! We have added this question to discuss during our plannings, and we will have in mind your implementation. There are a lot of questions around those offline pages for now.

**Comment by Sieg** [comment]
Hey @JaroslavHerber, How about - we will add the check if the "oxTriggerOfflinePageDisplay" is defined, so you could write your own?

**Comment by Loesdau** [comment]
Hey @Sieg, so you mean you would move oxTriggerOfflinePageDisplay to overridablefunctions.php with function_exists() check? And this function could be overwritten in /modules/functions.php for example?
This sounds great too :)

**Comment by JaroslavHerber** [comment]
Sorry for the last comment from another account. Thats was me 😅

**Comment by Sieg** [comment]
Hello @JaroslavHerber, I have merged what I was talking about :) (https://github.com/OXID-eSales/oxideshop_ce/commit/bf39ed6276f40291932cd523bf3bff631d9e2ad9) Hope that will help. Have a nice day!

**Pull request closed without merging**
