### PR TITLE
Remove duplicated if-statement

### PR DESCRIPTION
**Pull request by marvinhagemeister**

### CODE REVIEW

**Comment by kermie** [comment]
@marvinhagemeister - the boys love your pull request and would like to merge it. Can you please sign an OCA which is policy? https://github.com/OXID-eSales/oxideshop_ce/blob/b-dev-ce/CONTRIBUTING.md

**Comment by marvinhagemeister** [comment]
@kermie done, just signed the CLA

**Comment by kermie** [comment]
got it, thanks ;)

**Comment by Sieg** [comment]
Thanks @marvinhagemeister. PR merged.

**Pull request closed without merging**
