### PR TITLE
Improved default e-mail validator expression

### PR DESCRIPTION
**Pull request by SvenBrunk**
no longer accepted:
sven.brunk@-.-,-,-.oxid-esales.com
sven.brunk@-esales.com

### CODE REVIEW

**Comment by SvenBrunk** [comment]
Remark: I escaped some more characters than needed: within [] escaping + and . is actually not needed

**Comment by SvenBrunk** [comment]
nice! Github also does it wrong 🗡 🤣

**Comment by Sieg** [comment]
Hi @SvenBrunk, thanks for the improvement! So as i understood, the main point was to add the "+" symbol possible, right?

What could be improved in the suggested version:

- "{0,1}" part could go as just "?"
- we are missing the "\." part from original expression now, was it bad? the email like "itis@working" is fine with your variant.

I would also suggest considering usage of native PHP functionality as default filter - filter_var('bob@example.com', FILTER_VALIDATE_EMAIL), what do you think?

**Comment by flow-control** [comment]
Hey @Sieg,

@SvenBrunk and i discussed that, and we came to the conclusion, that switching to `filter_var` would be the best solution, but not that easily doable when we do not want to to a bc break, as the API would change in that case.
We could change it to use `filter_var` for the next major release though.

/Flo

**Comment by flow-control** [comment]
Additional Info: we can remove the `getMailValidationRule`, `setMailValidationRule` and the `__construct` Methods in that case. I would totally go for it, but that would be a BC Break ;-)

**Comment by flow-control** [comment]
I removed the reg ex completely in #725, so we could merge this into the current dev and merge the other on in master, what do you think @Sieg ?

**Comment by Sieg** [comment]
@flow-control, @SvenBrunk Hey guys! What about just extracting the Default case and run it if we are not setting new rules?, so, lets say, we have rule as null, and if its null, we are using the default filter_var for checking the email, otherwise, we use what Developer wants. That will be BC compatible, and will use filter_var by default?

**Comment by flow-control** [comment]
I would be ok with that @Sieg, but in the long run i would prefer to remove that altogether with the next major release. If someone still want's to check the email validity with it's own regular expression, the `MailValidator` class can be overloaded.

**Comment by flow-control** [comment]
Hey @SvenBrunk,
@Sieg and i had a discussion about this and we think that we could push this even further towards the `filter_var` thing. Could you add that as a default in the `isValidEmail` Method by checking if `self::__sMailValidationRule` is still `null` and if so, call `filter_var` and if not, use the regex.

/Flo

**Comment by Sieg** [comment]
Hello, Thank you for your ideas! After some internal discussions, there are EmailValidatorService and EmailValidatorServiceBridge introduced. Please use those instead of old stuff!

**Pull request closed without merging**
