### PR TITLE
nopic image file generation for unavailable png and gif files

### PR DESCRIPTION
**Pull request by preethi-sivasankaran**
imagecreatefrompng was used to create the target image in the method OxPicGenerator::resizePng() without considering the source image format. Hence when a false image was requested in any format other than jpg(since nopic file currently present in jpg), no image gets printed. With this solution, if an unavailable png file is requested, a nopic.png is generated and output. The same goes for GIF images too.

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
i found duplicate code in this pull request please consider to merge 
https://github.com/preethi-sivasankaran/oxideshop_ce/pull/1
https://github.com/preethi-sivasankaran/oxideshop_ce/pull/2
they will extract duplicate code.

**Comment by robertblank** [comment]
Hello @preethi-sivasankaran could you please pull the latest changes from OXID-eSales:master, rebase your branch onto it, resolve the conflicts and update your PR?

Thanks a lot

**Comment by preethi-sivasankaran** [comment]
Hello @robertblank , the conflicts have been resolved and required changes have been made

**Comment by robertblank** [comment]
Thank you for your work.
The pull request was backported to v5.3 and merged to b-5.3.
The PR was modified a little as we agreed in the team, that it was better to generate a nopic.jpg in any case and not to generate nopic.gif and nopic.png.
As for v6.0 I decided to do a refactoring of the class DynamicImageGenerator and the corresponding tests. Changes were merged into master.

**Pull request closed without merging**
