### PR TITLE
6056 oxprice smarty tag widget minibasket total

### PR DESCRIPTION
**Pull request by preethi-sivasankaran**
Adding oxprice smarty tag to display the price in the minibasket widget

### CODE REVIEW

**Comment by Sieg** [comment]
Hi, thanks for pull request! As i see, only 5267a43 should be taken from this pull request.

**Comment by hkreuter** [comment]
Hi, 
5267a4325520a79c27e3a06a4edf510b19ee1cb1 does not work for me unless unformatted prices (getNettoSum/getBruttoSum) are used.

**Comment by keywan-ghadami-oxid** [comment]
Hi Heike, unformated price should be used here. it did work for @preethi-sivasankaran because she also modified oxprice smarty-function to convert the formated sting back to float in her commit.

**Comment by hkreuter** [comment]
I overlooked the commit to oxprice smarty plugin, where the already formatted price is converted back to float. So the PR should work fine without changes but:
It should not be the task of any model class to bother about output formatting. What we would do now is get a formatted price from the model class and then convert it back and forth in a smarty plugin. Better use the unformatted price from the model and then let the view layer take care about how to display it.

**Comment by rezonanc-oxid** [comment]
Hi, Preethi, would it be possible for you to double check the failing test? `PluginSmartyOxPriceTest::testFormatPrice_badPriceOrCurrency`.

As you might noticed we're now using the Flow theme as our main theme with OXID eShop, could you please try and port it for the Flow theme (https://github.com/OXID-eSales/flow_theme).

**Comment by preethi-sivasankaran** [comment]
Hi Edvinas,
I have made the required changes to the test "PluginSmartyOxPriceTest::testFormatPrice_badPriceOrCurrency". I will separately include the same fix to the Flow theme repo.

**Comment by AMartinNo1** [comment]
As datatype prefixes are used in that scope:

`$sPrice = ($mPrice instanceof \OxidEsales\EshopCommunity\Core\Price) ? $mPrice->getPrice() : floatval($mPrice);`

--> https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Core/Price.php#L184

Shouldn't it be saved in `$fPrice` or `$dPrice`?

**Comment by Sieg** [comment]
Thank you, changes have been merged to master!

**Pull request closed without merging**
