### PR TITLE
Improve offline.html

### PR DESCRIPTION
**Pull request by marvinhagemeister**
+ Make html valid
+ Add a small maintenance note
+ Automatically attempt to redirect to index.php every 10 seconds

### CODE REVIEW

**Comment by proudcommerce** [comment]
hey @marvinhagemeister 
please use our branch for your pull request, thanks:
https://github.com/proudcommerce/oxideshop_ce/tree/ps_offlinepage

**Comment by proudcommerce** [comment]
reminder
hey @marvinhagemeister 
please use our branch for your pull request, thanks:
https://github.com/proudcommerce/oxideshop_ce/tree/ps_offlinepage

**Comment by Shiftas** [comment]
Hi, could you please rebase your branch as we have accepted #323 pull request?

**Comment by marvinhagemeister** [comment]
Of course, will do so tomorrow at lunch

**Pull request merged**
