### PR TITLE
read settings from theme.php like in metadata.php

### PR DESCRIPTION
**Pull request by alfredbez**
example theme.php:

``` php
$aTheme = array(
    'id'          => 'azure',
    'title'       => 'Azure',
    'description' => 'Azure theme by OXID eSales AG',
    'thumbnail'   => 'theme.jpg',
    'version'     => '1.4.1',
    'author'      => 'OXID',
    'settings' => array(
        array('group' => 'general', 'name' => 'sSomeName', 'type' => 'str', 'value' => 'default value'),
    ),
);
```

### CODE REVIEW

**Comment by roman-1983** [comment]
👍

**Comment by gregorhyneck** [comment]
Hi alfredbez,
the idea is nice, especially if you are working with multiple themes. In order to accept the pull request, - its necessary that you cover your new feature with tests
- ensure, that existing tests still run (use e.g. oxvm_eshop for local development)
Thank you!

**Comment by keywan-ghadami-oxid** [comment]
Hi @alfredbez, i like to point out that i am very thankful for this pull request. From now you have write access to my fork you can use as incubator for what ever you like and others will be able to commit to your feature branches (or rebase them).

**Comment by alfredbez** [comment]
@keywan-ghadami-oxid I pushed my branch to your fork: https://github.com/keywan-ghadami-oxid/oxideshop_ce/tree/feature-readSettingsFromTheme

**Comment by alfredbez** [comment]
What's the best way to handle theme settings with the same name in different themes?
Example:
`themeA/theme.php`
```php
$aTheme = array(
	'id'       => 'themeA',
	'settings' => array(
	  array(
	    'group' => 'groupName',
	    'name'  => 'thisIsAName',
	    'type'  => 'str',
	    'value' => 'oneValue',
	  ),
	)
);
```
`themeB/theme.php`
```php
$aTheme = array(
	'id'       => 'themeB',
	'settings' => array(
	  array(
	    'group' => 'groupName',
	    'name'  => 'thisIsAName',
	    'type'  => 'str',
	    'value' => 'anotherValue',
	  ),
	)
);
```
When an user activates themeA, `thisIsAName` will be set to `oneValue`. What should happen, when the user activates themeB? Should `thisIsAName` be set to `anotherValue`? Or is it better to leave it as `oneValue`?
Current behaviour will not override it.
The safest way to prevent collision with other theme settings is probably to prefix all variables (e.g. `MYVENDOR_thisIsAName` or `themeA_thisIsAName`).

**Comment by keywan-ghadami-oxid** [comment]
i think the old value should stay, i think it's good to take the configured value from an other theme as default value so there is a chance that the user does not need to configure things again and programmer can make themes compatible by using the same configuration name.

**Comment by alfredbez** [comment]
I refactored and rebased it, if there is anything else you need, please, let me know.

**Comment by floeschie** [comment]
This looks like a cool feature! @Sieg does this fit into our new template lookup mechanism? If yes, then ACK for merge.

**Comment by Sieg** [comment]
Yup, the pr removes the need of sql file imports for installing themes.

**Comment by Sieg** [comment]
Thank you @alfredbez for the pull request. We will discuss some questions and do some improvements/cleanups internally so the pull request will be merged soon.

**Comment by floeschie** [comment]
@alfredbez FYI: We will talk about this pull request in today's product backlog grooming. Afterwards we will do a rough estimation for clean-up and finalization, and then enqueue it for prioritization with other change requests.

**Comment by floeschie** [comment]
Hi all, this thing needs further discussion. It is recorded to the backlog as ESDEV-3851, however it is not prioritized and "ready for development" yet.

There were some questions in the backlog grooming, for example if the module activation workflow should be changed from "first activate, then configure" to "first configure, then activate". Furthermore there was a discussion if the configuration file(s) of OXID eShop extensions (this includes modules as well as themes) should  all have the same name (e. g. "metadata.php"), or if this would lead to confusion, as the ```metadata.php``` for modules would have a different content structure as the ```metadata.php``` file for themes.

@kermie suggested to discuss this with @alfredbez and some rep's of the core team in a video chat. Would that be okay?

**Comment by keywan-ghadami-oxid** [comment]
Hi @floeschiei know this github communication creates a lot of emails, but anyway i would love to see discussion stay on github because me and everybody else can follow the discussen and bring in ideas, and contributions and will be able to understand decisions even years after code was written.

Please let me try to answer the questions the pull request does technically not do any desiccion about the filenames metadata or theme.php this decissions where already done in existing oxid esales code base . If it should be change some day from theme.php to metadata.php the code from this pull request is not directly affected because it is done aftere the file was read.

The pr also does not do a decision about the structure in any point but the 'settings', and personally i think it is good to find similar thing again in application because it help developers to chunk things and to reuse code.

Having that said the question is what should be improved to make this production ready and can things be seperated into improve after merge/and improve before merge because having things not merged for a long time will cause more work for all participants because conflicts must be resolved and tasks block eachother. 

Please do not take stuff above as criticism i am very proid, because PRs in oxid getting that much attention and things are beeing discussed and improved, thats making the different to some other opensource :+1: 

One last word

**Comment by alfredbez** [comment]
If the activation workflow should be changed it should be "first configure, then activate" over "first activate, then configure" I'd say. Nobody wants an activated theme/module with missing configuration.

I would suggest to create a `settings.php` which is similar for themes and for modules and to load that file automatically if it exists.

@floeschie We can do a video call, however I like also what @keywan-ghadami-oxid said.

**Comment by alfredbez** [comment]
ping? 4 months since last commit

**Comment by MantasVaitkunas** [comment]
@alfredbez, team and PO will discuss about this PR during backlog grooming session which will be on Wednesday. Hang on!

**Comment by MantasVaitkunas** [comment]
Hello again, we all agreed that this PR will have to be accepted before release of 6.0 beta, so 6.0 will have this feature. Unfortunately I can't say exact date when it will be merged. Hang on!

**Comment by alfredbez** [comment]
This should be updated after merge: http://oxid-eshop-developer-documentation.readthedocs.io/en/latest/themes/index.html

**Comment by keywan-ghadami-oxid** [comment]
The link to the repository: https://github.com/OXID-eSales/developer_documentation/tree/master/themes

**Comment by MantasVaitkunas** [comment]
Changes were merged with separate branch.

**Pull request closed without merging**
