### PR TITLE
6539: split selectlists and varselect

### PR DESCRIPTION
**Pull request by alfredbez**
This fixed [6539](https://bugs.oxid-esales.com/view.php?id=6539), I described the problem and steps to reproduce there.

I introduced a new delimiter `||` if a value from a selectlist and a variant are selected.

To make things testable I changed `$oProduct->oxarticles__oxvarselect->getRawValue()` to `$oContent->getVarSelect()`, since we're using this already for selectlists (`$oContent->getChosenSelList()`).

I also added a `break` to a foreach loop in `getOrderArticleSelectList()` because we don't need to check all other selectlist values if we already found a matching one.

You can test the wrong behaviour with [this failing test](https://gist.githubusercontent.com/alfredbez/ad9ac3740b07f2ebf60068017121dec1/raw/999cd0a8aa5f22cd0f913507c7f9037bc4d25f73/failing_test.patch):
```patch
diff --git a/tests/Unit/Application/Model/OrderarticleTest.php b/tests/Unit/Application/Model/OrderarticleTest.php
index 62d65fa..2303a13 100644
--- a/tests/Unit/Application/Model/OrderarticleTest.php
+++ b/tests/Unit/Application/Model/OrderarticleTest.php
@@ -431,6 +431,11 @@ class OrderarticleTest extends \OxidTestCase
         $sFields = "Color : red, Material : wood ";
         $oOrderArticle = oxNew('oxOrderArticle');
         $this->assertEquals(array(0 => 0), $oOrderArticle->getOrderArticleSelectList('1126', $sFields));
+
+        // articles with selectlists and variants should work
+        $sFields = "Color : red variantvalue1 | variantvalue2";
+        $oOrderArticle = oxNew('oxOrderArticle');
+        $this->assertEquals(array(0 => 0), $oOrderArticle->getOrderArticleSelectList('1126', $sFields));
     }
 
     public function testMakeSelListArrayPriceON()
```

### CODE REVIEW

**Comment by alfredbez** [comment]
It would be nicer if we could create a new field like `oxselectlistvalue` in `oxorderarticles`

**Comment by alfredbez** [comment]
**Example**

<table>
<tr>
  <td>Article</td>
  <td>shirt</td>
</tr>
<tr>
  <td colspan="2">Variants</td>
</tr>
<tr>
  <td>color</td>
  <td>red, blue</td>
</tr>
<tr>
  <td>size</td>
  <td>s, m, l</td>
</tr>
<tr>
  <td colspan="2">Selectlists</td>
</tr>
<tr>
  <td>someSelectlist</td>
  <td>firstValue, secondValue, thirdValue</td>
</tr>
</table>

User buys Article "shirt" with the following selection:
<table>
<tr>
  <td>variant</td>
  <td>red & s</td>
</tr>
<tr>
  <td>selectlist</td>
  <td>secondValue</td>
</tr>
</table>

`OXSELVARIANT` becomes: `someSelectlist : secondValue | red | s`  
see:
```
$oOrderArticle->oxorderarticles__oxselvariant = new oxField(trim($sSelList . ' ' . $oProduct->oxarticles__oxvarselect->getRawValue()), oxField::T_RAW);
```

---

**Problem:** The delimiter ` | ` is used to separate each variant, but also to separate the variant-selection and the selectlist.

**My suggested solution:** Use ` | ` to separate each variant and ` || ` to separate the variant-selection and the selectlist. So `OXSELVARIANT` becomes: `someSelectlist : secondValue || red | s`

**Comment by alfredbez** [comment]
I've resolved the merge conflicts.

**Comment by Sieg** [comment]
Hello @alfredbez, i have merged the fix to b-6.1.x recently on 5b7de69e6191466b43de6601066451df757f1198

**Pull request closed without merging**
