### PR TITLE
Fix a typo in javascript plugin name and update its usages accordingly

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fix a small typo in oxUserShippingAddress

### CODE REVIEW

**Comment by ooxi** [comment]
I think you forgot to rename the `oxusershipingaddressselect.js` file :)

**Comment by marvinhagemeister** [comment]
It's renamed correctly. Renamed files are easy to miss in PRs (missed it myself). Right below the filename is a small arrow followed by the new filename ;)

**Comment by ooxi** [comment]
> .../js/widgets/oxusershipingaddressselect.js → ...js/widgets/oxusershippingaddressselect.js

aaah!

**Comment by Sieg** [comment]
Hi @marvinhagemeister, Thank you for your pull request. Merged it.

**Pull request closed without merging**
