### PR TITLE
Cache jQuery elements

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Some low hanging render improvements. Storing an object is way cheaper than traversing the DOM.

### CODE REVIEW

**Comment by Sieg** [comment]
Hi Marvin, 

I have rebased your commit on our master branch. There are a bunch of selenium tests failing. Could you please check it out and fix the issues?

Some of the test files to check first:

```
OxidEsales\Eshop\Tests\Acceptance\Frontend\BasketFrontendTest
OxidEsales\Eshop\Tests\Acceptance\Frontend\MyAccountFrontendTest
OxidEsales\Eshop\Tests\Acceptance\Frontend\UserRegistrationFrontendTest
```

**Comment by marvinhagemeister** [comment]
@Sieg Thanks! I'll fix them once I manage to actually be able to run the tests (selenium always times out for me). I'll investigate again next week

**Comment by MantasVaitkunas** [comment]
@marvinhagemeister if you are using https://github.com/OXID-eSales/oxvm_eshop maybe there is a configuration issue. In the personal.yml there is a need to add:
```
selenium:
  install: true
```

**Comment by MantasVaitkunas** [comment]
@marvinhagemeister, I am going to close this PR. As you know, Flow theme is now the preferred choice. Also, in the meantime, the branch already conflicted. How should we proceed with this?

**Pull request closed without merging**
