### PR TITLE
add getStock()

### PR DESCRIPTION
**Pull request by tabsl**
- returns oxarticles__oxstock
- place to hook for other stock changing actions

### CODE REVIEW

**Comment by mattvb91** [comment]
:+1:

**Comment by mattvb91** [comment]
@Sieg any chance you can give us an update on why pull requests like this (and others) are taking so long to review?

I would understand if this was a huge amount of changes but Oxid is making it really difficult to stay motivated enough to open pull requests when even stuff like this doesnt make it in after months with no response...

**Comment by tabsl** [comment]
any update?

**Comment by keywan-ghadami-oxid** [comment]
@tabsl would it be more useful to make that method public?

**Comment by tabsl** [comment]
@keywan-ghadami-oxid oh, damn ;-) fixed ...

**Comment by Sieg** [comment]
Hi @tabsl, thanks for your pull request. Merged to b-6.x recently on 0fddcb620301bf1e0b68baccf713b6674c07451e

**Pull request closed without merging**
