### PR TITLE
Reduce php notices

### PR DESCRIPTION
**Pull request by Trainmaster**
This will fix some PHP notices:
```
Undefined variable: sContent in /xxx/core/smarty/plugins/function.oxid_include_dynamic.php on line 60
Undefined variable: sCacheIdent in /xxx/application/models/oxtagcloud.php on line 191
Undefined variable: aCloudArray in /xxx/application/models/oxtagcloud.php on line 181
Undefined index: __oxid_include_dynamic in /xxx/core/smarty/plugins/function.oxscript.php on line 48
Undefined index: noscript in /xxx/core/smarty/plugins/function.oxid_include_widget.php on line 38
Undefined index: ajax in /xxx/core/smarty/plugins/insert.oxid_newbasketitem.php on line 53
Trying to get property of non-object in /xxx/core/oxfunctions.php on line 309
Undefined variable: oWrappingCost in /xxx/application/models/oxbasket.php on line 1326
Undefined index: PAGE_TITLE_START in /xxx/core/oxlang.php on line 437
Undefined variable: sShopId in /xxx/core/oxseoencoder.php on line 372
Undefined variable: sShopId in /xxx/core/oxseoencoder.php on line 390
Undefined variable: sShopId in /xxx/core/oxseoencoder.php on line 393
Undefined variable: blAdmin in /xxx/core/smarty/plugins/function.oxinputhelp.php on line 43
```

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @Trainmaster, could you please check the status on Travis?

**Comment by Trainmaster** [comment]
@Sieg I rebased on `b-5.3-ce` but I'm somehow lost with the errors on Travis. Is `b-5.3-ce` the right target branch?

**Comment by Trainmaster** [comment]
@kermie Should I change the target branch?

**Comment by kermie** [comment]
@Trainmaster looks like the actual problem is not about the branch but about a failed Travis test. @Sieg can you please help out to explain what exactly went wrong? Mayhap, tests have to be adapted accordingly.

**Comment by Trainmaster** [comment]
@Sieg @kermie One last try ... I rebased onto latest `b-5.3-ce` but there appear still many errors which are not related to my changes. Should i close this MR?

**Comment by keywan-ghadami-oxid** [comment]
@Trainmaster Hi thank you for your pull request, I did a quick code review and saw this more then only fixing warnings it may also fix issues and looks promising.

I am by myself not a core developer, but I think you should better rebase to the master branch, because 5.3 branch is not likely to get that kind of improvements. But be aware that in the master branch (version 6) a lot of classes are moved to different places so git will not be able to apply you changes automatically in the correct files. So I guess you don't want to do all the work again. The good news are, you may not have to do so because in version 6 of oxid a lot of this stuff may be already fixed.

**Pull request closed without merging**
