### PR TITLE
Database driver options config

### PR DESCRIPTION
**Pull request by spatricius**
Allow to pass custom database driver options from withing config.inc.php. 

For example this is needed to establish a database connection over SSL (to pass a certificate path).

Example with just PDO:
```
<?php
$servername = "test.com";
$username  = "oxid@test";
$password = "test";
$options = array(
	PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
	PDO::MYSQL_ATTR_SSL_CA => 'cert.crt.pem',
	PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
);

try {
    $conn = new PDO("mysql:host=$servername;port=3306;dbname=mysql", $username, $password, $options);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Connected successfully"; 
        var_dump($conn->query("SHOW STATUS LIKE 'Ssl_cipher';")->fetchAll());
        $conn = null;
}
catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
}
?>

```

With OXID, I found it difficult to implement, as I needed to extend both 
`OxidEsales\Eshop\Core\Database\Adapter\Doctrine\Database`
and
`OxidEsales\Eshop\Core\DatabaseProvider`
then initialize the connection in a few places:
- source/modules/functions.php (called from bootstrap) for http requests
- all console scripts (views, config, migrations) - I created wrappers to include bootstrap first

With the proposed change it would be possible to just define custom connection options in config.inc.php like so:
```
$this->dbDriverOptions = [
    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
    PDO::MYSQL_ATTR_SSL_CA => 'cert.crt.pem',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
];
```

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
@spatricius awesome by chance will this change also allow to use sockets for db connection like I do here by injecting options to the hostname:
https://github.com/OXIDprojects/oxid-console/blob/36d16477f166826c4d8cb8ef88b79ec69a51eb6b/.github/workflows/check.yml#L31
but in a clean way?

**Comment by spatricius** [comment]
Hi Keywan, 

> @spatricius awesome by chance will this change also allow to use sockets for db connection

We can do it like in [this commit](https://github.com/OXID-eSales/oxideshop_ce/pull/753/commits/ac3f43fbefed4fb35b03ba221a1af4a492aa50c7)

Then in config.inc.php:

`$this->dbUnixSocket = '/var/run/mysqld/mysqld.sock';`

**Comment by Sieg** [comment]
Hello @spatricius, could you please rebase this on our latest master and reopen the pull request?

**Comment by spatricius** [comment]
sure

**Pull request closed without merging**
