### PR TITLE
Fix � in Setup

### PR DESCRIPTION
**Pull request by alfredbez**
before:
image

after:
image

### CODE REVIEW

**Comment by kermie** [comment]
Is it PHP 5.6 related? Am not sure if not the header has to be adapted as well.

**Comment by ooxi** [comment]
Yea without changing of the HTTP Content-Type header or HTML meta charset, the change cannot work in all browsers.

**Comment by alfredbez** [comment]
> Is it PHP 5.6 related?

I've tested this in two different vagrant boxes (5.6 and 7.0) and both show me the same result.

HTTP Content-Type is `Content-Type: text/html; charset=UTF-8` (in Chrome DevTools)

**Comment by Crease29** [comment]
The charset header is UTF-8 because it's the default charset header since PHP 5.6.
What about PHP versions < 5.6?

**Comment by keywan-ghadami-oxid** [comment]
@Crease29 so you suggest to add 
```php
//explicitly set utf8 for php < 5.6
header('Content-Type: text/html; charset=utf-8');
```
into
https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Setup/index.php

**Comment by Crease29** [comment]
Exactly @keywan-ghadami-oxid. Wouldn't it be the best solution to switch OXID eShop completely to UTF-8, nowadays?

**Comment by keywan-ghadami-oxid** [comment]
@Crease29 we already did some steps to go that way, we always have to consider things like performance and compatibility, but i totally agree that we should keep on moving to utf8 everywhere.

**Comment by Shiftas** [comment]
Well, the suggested solution would work properly for use with PHP 5.6 and higher. Unfortunately, it will break for use with PHP 5.5 and lower so we have to find another solution that fits all PHP versions. We'll merge this pull request and add the universal solution for it.

**Comment by keywan-ghadami-oxid** [comment]
for those interested in technical details of the chosen implementation:
- the setup sends know http header with utf8,
- and setup language files are also switched to utf8 encoding,
- html meta tag was used to force utf8.  
-- more details about that tag: http://stackoverflow.com/questions/4696499/meta-charset-utf-8-vs-meta-http-equiv-content-type
see also other commits
https://github.com/OXID-eSales/oxideshop_ce/commit/562e79f2b44d405c5bfaded863fd37ac23763668

**Pull request closed without merging**
