### PR TITLE
Adding not documented [symbol position] parameter in shop_config.tpl

### PR DESCRIPTION
**Pull request by gerlweb**
ok, now hopefully on the right way

### CODE REVIEW

**Comment by kermie** [comment]
Hi @gerlweb, 
thanks for your commit, that we likely want to merge into V6. We still want to fix the tests before (whatever went wrong there...). Please take care you submit sufficient descriptions with your pull requests. Cheers!

**Comment by gregorhyneck** [comment]
Relates to https://bugs.oxid-esales.com/view.php?id=5837

**Comment by gerlweb** [comment]
Hi Marco,
thanks for review1 Next time i'll do the full description.

**Comment by gregorhyneck** [comment]
The Pull Request was merged together with pull request 548:
commit https://github.com/OXID-OSales/oxideshop_ce/commit/7c62d9069ca8139aad12ad8699bd11803074d3b7 into master of OXID eShop 6. Some modifications of multilang texts were done.

**Pull request closed without merging**
