### PR TITLE
vat message for b2b users with valid ustid

### PR DESCRIPTION
**Pull request by keywan-ghadami-oxid**
vat messages say vat is included in the price but that's wrong
https://bugs.oxid-esales.com/view.php?id=6516

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
just realized that there might be a better way to fix this by using getUserVat from VatSelector class
https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Application/Model/VatSelector.php#L59

**Comment by Sieg** [comment]
Hello @keywan-ghadami-oxid, thanks for your pull request. Are you planning to make further improvements on this pull request?

**Comment by Sieg** [comment]
Hello @keywan-ghadami-oxid, some points to update the pull request:
* Cant we use getFieldData method to get values?
* How about strict comparison for values (===) so checking for null will be not needed.

**Comment by Sieg** [comment]
Thank you for your pull request. I have merged it at fa16a934e74a3425a3261c514f7176a707759349. Have a nice day.

**Pull request closed without merging**
