### PR TITLE
oxactive filter missing in DB fetch in OxContent.php

### PR DESCRIPTION
**Pull request by preethi-sivasankaran**
Applied oxactive filter to DB Fetch from oxcontent. Now Help Page link in footer is displayed according to the oxhelpdefault CMS Page.

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
i am wondering if the  _loadFromDb is the right place to add that condition, because it is responsible for fetching that object from the database, and so it might become impossible to change that active setting back.

I suggest to add an parameter to loadByIdent Method and check "oxactive" there.

**Comment by Sieg** [comment]
Hi @preethi-sivasankaran, As Keywan already told, that method cannot be responsible for getting Only active items.
Why can't we just check if Content is active after loading it? Lets say with Content::isActive() method?

**Comment by preethi-sivasankaran** [comment]
The required changes have been made

**Comment by Sieg** [comment]
Could you please rebase on our master?

**Comment by hkreuter** [comment]
Hi Preethi, 
could you please check your latest commit? Looks like you had conflicts during rebase, Classes source/Application/Model/oxcontent.php  and source/Core/oxviewconfig.php are deprecated in b-dev and should not be used anymore.

**Comment by preethi-sivasankaran** [comment]
Hi All, 
I am updating this pull request now. Will update the required changes once the corrections have been made.
-Preethi

**Comment by preethi-sivasankaran** [comment]
Hi All,
All required changes have been made, unit testcase added and rebased to OXID-eSales/oxideshop_ce master. 
-Preethi

**Comment by Sieg** [comment]
Hi @preethi-sivasankaran, i am sorry, but some more problems found on latest review of the changes, when tested with our other editions and caching mechanics :(. Will write you more in near future, after discussion with the team.

**Comment by Sieg** [comment]
Thank you @preethi-sivasankaran for your work! I have just merged your pull request with some additional changes on the top.

**Pull request closed without merging**
