### PR TITLE
add setStockStatus()

### PR DESCRIPTION
**Pull request by proudcommerce**

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @proudcommerce, could you please describe more, why we need to set this flag manually?

**Comment by tabsl** [comment]
Changing this flag through a module?! ;-)[@proudcommerce]

**Comment by Sieg** [comment]
So if we need to change it in the module, its possible to extend the article as well, in the module, and add the method there. Are there any use cases it should be in the article class itself?

**Comment by tabsl** [comment]
I can’t say it exactly anymore, but we needed it ...

**Comment by Sieg** [comment]
No, you don't.

**Comment by Sieg** [comment]
Please reopen the pull request if there will be a list of use cases for this method, otherwise, we don't see any point to add it - as mentioned already, this flag is calculated on loading and stock recalculation actions, and by the idea, should not be changed manually.

**Pull request closed without merging**
