### PR TITLE
fixed some phpcs errors

### PR DESCRIPTION
**Pull request by alfredbez**

### CODE REVIEW

**Comment by alfredbez** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by alfredbez** [comment]
The travis build failed again and I think, that this is not related to this PR:
```
There was 1 error:

1) Unit\Application\Model\UserTest::testOnOrderExecute0
OxidEsales\Eshop\Core\Exception\DatabaseException: Duplicate entry 'oxidnotyetordered-b7e2dfc112f85fb07fe656c13164bea6-1' for key 'UNIQ_OBJECTGROUP'

/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:892
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:739
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:544
/home/travis/build/OXID-eSales/oxideshop_ce/tests/Unit/Application/Model/UserTest.php:1726
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/oxid-esales/testing-library/library/UnitTestCase.php:163

Caused by
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'insert into oxobject2group (oxid,oxshopid,oxobjectid,oxgroupsid) values ( "d935f7006e876a0b2b24eeabfab82f1b", "1", "b7e2dfc112f85fb07fe656c13164bea6", "oxidnotyetordered" )':
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'oxidnotyetordered-b7e2dfc112f85fb07fe656c13164bea6-1' for key 'UNIQ_OBJECTGROUP'

/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:737
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:544
/home/travis/build/OXID-eSales/oxideshop_ce/tests/Unit/Application/Model/UserTest.php:1726
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/oxid-esales/testing-library/library/UnitTestCase.php:163

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'oxidnotyetordered-b7e2dfc112f85fb07fe656c13164bea6-1' for key 'UNIQ_OBJECTGROUP'

/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:737
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:544
/home/travis/build/OXID-eSales/oxideshop_ce/tests/Unit/Application/Model/UserTest.php:1726
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/oxid-esales/testing-library/library/UnitTestCase.php:163

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'oxidnotyetordered-b7e2dfc112f85fb07fe656c13164bea6-1' for key 'UNIQ_OBJECTGROUP'

/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:737
/home/travis/build/OXID-eSales/oxideshop_ce/source/Core/Database/Adapter/Doctrine/Database.php:544
/home/travis/build/OXID-eSales/oxideshop_ce/tests/Unit/Application/Model/UserTest.php:1726
/home/travis/build/OXID-eSales/oxideshop_ce/vendor/oxid-esales/testing-library/library/UnitTestCase.php:163
```

I saw the exact same message multiple time in different builds. I trigger a new build...

**Comment by alfredbez** [comment]
I resolved the merge conflicts and rebased it.
> Code sniffer check passed successfully! Errors count is 101, threshold is set to 155.

**Comment by rezonanc-oxid** [comment]
Hi,

I see good intentions and nice work! One small issue though, it seems that the commit is not as atomic as it should be, i.e. there are parts that are not related to the same issue:

* https://github.com/OXID-eSales/oxideshop_ce/pull/505/commits/71695bd0d9305c909f329f8fbb719cce9ee9790e#diff-3f8d458575c376b46f980c4824182453R4370
* https://github.com/OXID-eSales/oxideshop_ce/pull/505/commits/71695bd0d9305c909f329f8fbb719cce9ee9790e#diff-97d1e0a82d5add5ec768e1eb2076018dR423
* https://github.com/OXID-eSales/oxideshop_ce/pull/505/commits/71695bd0d9305c909f329f8fbb719cce9ee9790e#diff-97d1e0a82d5add5ec768e1eb2076018dR496

If the commit would have been atomic, we would have merged it to the master already without further investigation.

I would also would like to know your opinion on this. Do you agree with the conclusion? Would it be possible to make the changes (revert not related changes) from your side?

**Comment by alfredbez** [comment]
Hello,
the  parts you mentioned lower the cyclomatic complexity. You see this by running this command:
```
vagrant@oxideshop:/var/www/oxideshop$ vendor/bin/phpcsoxid source/Core/DynamicImageGenerator.php

FILE: /var/www/oxideshop/source/Core/DynamicImageGenerator.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 78 | ERROR | USE declarations must go after the first namespace
    |       | declaration
 79 | ERROR | USE declarations must go after the first namespace
    |       | declaration
 80 | ERROR | USE declarations must go after the first namespace
    |       | declaration
----------------------------------------------------------------------

Time: 773ms; Memory: 9.75Mb
```
Without these changes:
```
vagrant@oxideshop:/var/www/oxideshop$ vendor/bin/phpcsoxid source/Core/DynamicImageGenerator.php

FILE: /var/www/oxideshop/source/Core/DynamicImageGenerator.php
----------------------------------------------------------------------
FOUND 8 ERRORS AND 2 WARNINGS AFFECTING 10 LINES
----------------------------------------------------------------------
  78 | ERROR   | USE declarations must go after the first namespace
     |         | declaration
  79 | ERROR   | USE declarations must go after the first namespace
     |         | declaration
  80 | ERROR   | USE declarations must go after the first namespace
     |         | declaration
 413 | WARNING | Function's cyclomatic complexity (13) exceeds 10;
     |         | consider refactoring the function
 496 | WARNING | Function's cyclomatic complexity (15) exceeds 10;
     |         | consider refactoring the function
 759 | ERROR   | Doc comment for parameter "$filePath" missing
 762 | ERROR   | Missing parameter name
 771 | ERROR   | Doc comment for parameter "$imageFilePath" missing
 775 | ERROR   | Missing parameter name
 776 | ERROR   | Missing @return tag in function comment.
----------------------------------------------------------------------

Time: 587ms; Memory: 9.75Mb
```
However I'll make a seperate pull-requests for those changes so that you can merge this one.

**Comment by rezonanc-oxid** [comment]
Yes, you're correct! I have looked at that part only with my "naked eye" and haven't noticed that the intention was to reduce the cyclomatic complexity as well.

Thanks for caring about our sniffer errors and helping to eliminate them!

**Comment by rezonanc-oxid** [comment]
I've also lowered the OXID_ESHOP_CS_THRESHOLD variable to motivate everyone in lowering the number of sniffer errors that we have.

Hope we will reach 0 eventually! ;)

**Pull request merged**
