### PR TITLE
do not mess with error_reporting server setting

### PR DESCRIPTION
**Pull request by flow-control**
This pull requests removes resetting the PHP error reporting level via a call to `error_reporting()` in the `ShopControl` class.

I personally think it is not a good idea to mess with server settings in such a way, that it just overrides whatever the server settings are. In most cases the operator put thought in these settings and we should not mess with these.

### CODE REVIEW

**Comment by flow-control** [comment]
@Sieg do you think we can target `b-6.x` with this PR?

**Comment by flow-control** [comment]
Rebased on latest `master`

**Comment by flow-control** [comment]
Rebased on lastest `master` and pushed

**Comment by flow-control** [comment]
Depends on https://github.com/OXID-eSales/testing_library/pull/23 being merged upfront

**Comment by Sieg** [comment]
Hey @flow-control, this one is merged! :) Have a nice day!

**Pull request closed without merging**
