### PR TITLE
add block admin_voucherserie_groups_form

### PR DESCRIPTION
**Pull request by tabsl**

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @tabsl, i dont think this is good to add such a block. As i see, it takes 2 forms right now, and basically not very nicely - part of the first table and not whole second table taken into the block. Please double check the code.

**Comment by tabsl** [comment]
What´s your suggestion?

**Comment by Sieg** [comment]
Hi @tabsl, Please check my commit, will it fit your needs?

**Comment by Sieg** [comment]
Okay, merged at b3ffd212822df26b7cd0fdeaca3fc3c0ab40115a. Have a nice weekend!

**Pull request closed without merging**
