### PR TITLE
add actions widget

### PR DESCRIPTION
**Pull request by proudcommerce**
added widget for actions. so it´s possible to access all actions in all templates.
example in basket: show bestseller (oxtop5) below basket contents.
this pull request is referring to https://github.com/OXID-eSales/oxideshop_ce/pull/17

### CODE REVIEW

**Comment by tabsl** [comment]
hey guys, i searched for this feature in oxid 4.9.3 but didnt find it. can you say me, where´s the possibility to use an action in all templates?

**Comment by artsev-oxid** [comment]
Hi @tabsl,
Please forward this question to dev-general.

**Comment by tabsl** [comment]
already done, and now?

**Comment by artsev-oxid** [comment]
We will discuss your dev-general post today internally. Sorry for inconvenience.

**Comment by proudcommerce** [comment]
can you give us a short status update, please.

**Comment by stasiukaitis-saulius** [comment]
@proudcommerce accepted and merged to all needed places :)

**Comment by proudcommerce** [comment]
(y)

**Comment by proudcommerce** [comment]
template file in flow/wave theme is missing

**Pull request closed without merging**
