### PR TITLE
Reversed floating for Content First Approach, used hyphen-separated C…

### PR DESCRIPTION
**Pull request by mlabsch**
…SS selectors for better handling later on. Sorted CSS properties alphabetically for better overview. Fixed position of IF-Statement to avoid empty class attribute.

### CODE REVIEW

**Comment by ooxi** [comment]
Please use separate pull requests for independent changes :)

**Comment by mlabsch** [comment]
All changes are connected ... would love to if you can tell me where to separate ;)

**Comment by Shiftas** [comment]
merged with https://github.com/OXID-eSales/oxideshop_ce/commit/c1f7aff22f5b5b7f89f8bf687c891f8ed5bf1d62

**Comment by ooxi** [comment]
> All changes are connected ... would love to if you can tell me where to separate ;)

I would separate whitespace fixes from CSS fixes, but since it's merged already, no harm is done :)

**Pull request closed without merging**
