### PR TITLE
Fix linting errors

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR fixes lots of missing `var` keywords and prevents variables from leaking into the global scope by assigning them to the `window` object. This makes it easier to work with modern javascript bundlers like browserify or webpack.

### CODE REVIEW

**Comment by Shiftas** [comment]
Need to run acceptance tests on that, hang on.

**Comment by MantasVaitkunas** [comment]
Acceptance tests will be run within the next fortnight.

**Comment by Sieg** [comment]
Hi Marvin! I have run the selenium tests, and there are some problems in there.
As example: 
```
1) OxidEsales\Eshop\Tests\Acceptance\Frontend\ValidateUpdatedShopTest::testSearchAndCheckout
Timeout waiting for 'basketFlyout'.
2) OxidEsales\Eshop\Tests\Acceptance\Frontend\BasketFrontendTest::testFrontendBasketFlyout
Timeout waiting for '//div[@id='basketFlyout']//a[text()='Checkout']'.
3) OxidEsales\Eshop\Tests\Acceptance\Frontend\NavigationFrontendTest::testFrontendTags
Timeout waiting for 'newTags'.
4) OxidEsales\Eshop\Tests\Acceptance\Frontend\ProductInfoFrontendTest::testMdVariantsAndJs
Timeout waiting for 'basketFlyout'.
```
Could you please check those cases? 
We have rebased your changes on our master - feel free to check the marvinhagemeister-eslint_errors-Pull341 branch.

**Comment by marvinhagemeister** [comment]
Hi @Sieg 
That's awesome! Just rebased my branch against current master. I'd love to fix the selenium tests, although I currently get an error when I run phpunit alone. I guess I need to use https://github.com/OXID-eSales/oxvm_eshop ?

**Comment by Sieg** [comment]
I think it could be the easiest solution to run all the tests. Please, refer to the VM documentation how to configure it for running the selenium tests.

**Comment by marvinhagemeister** [comment]
Quick update: I haven't had any luck so far with the testing library. Each selenium test simply times out, I'll investigate further next week

**Comment by MantasVaitkunas** [comment]
@marvinhagemeister, I am going to close this PR. As you know, Flow theme is now the preferred choice. Also, in the meantime, the branch already conflicted. How should we proceed with this?

**Pull request closed without merging**
