### PR TITLE
Preparation for PHP7

### PR DESCRIPTION
**Pull request by kyoya-de**
After replacing the deprecated 'mysql_*' functions and changing the default ADODB driver to mysqli, the OXID setup is now compatible with (but not optimized for) PHP7.

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @kyoya-de, thanks for your pull request. We will most likely merge commit #9ef39b2 but must admit that it will take a bit of time because unit tests have to be streamlined and MySQLi has to be implemented into the CI.

**Comment by floeschie** [comment]
Added this PR to our Backlog, team will work on it soon.

**Comment by adriankirchner** [comment]
:+1:

**Comment by kyoya-de** [comment]
:+1:

**Pull request closed without merging**
