### PR TITLE
updated lang file until 'OXDISTEAN'

### PR DESCRIPTION
**Pull request by kermie**

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
@kermie unittest (see travis build on commit 4ec5350) are failing because wishlist_by and write_entry must also be deleted from german language files. The unittest ensures they have the same keys defined.

**Comment by kermie** [comment]
Are you sure @keywan-ghadami-oxid ? PR #446 was basically committed the same time as this one, doing the German files. Can't imagine travis was quicker than we were or that it is checking single PRs only ;)

**Comment by keywan-ghadami-oxid** [comment]
yes i am: it is checking single PRs only.
So if you need the green checkmark from travis you can merge PR446 and this(PR445) together and close one of the Pull requests.

**Comment by kermie** [comment]
Interesting, didn't know that. Cheers!

**Comment by MantasVaitkunas** [comment]
Hi @kermie,
In English translation file you removed constants WISHLIST_BY and WRITE_ENTRY, but these constants are still in German translation file. Why it was done like this?

**Comment by MantasVaitkunas** [comment]
Oh.. I get it, #446 is related... In the future please make one pull request as these files are related :)

**Pull request closed without merging**
