### PR TITLE
Update oxinputvalidator.php

### PR DESCRIPTION
**Pull request by ddpkts**
password length is configurable in admin, avoid hardcoded value

### CODE REVIEW

**Comment by hkreuter** [comment]
Hi, thank you for your contribution. We'd like to accept your pull request but unfortunately some tests are broken, could you please have a look at Travis CI and fix them first?

**Comment by ddpkts** [comment]
Hi Heike, 
sorry but it would take me too much time to do that, I will leave that for core developers.

**Comment by MantasVaitkunas** [comment]
@ddpkts seems to be on parental leave presently. Will merge this PR and write the tests as soon as possible.

**Comment by ddpkts** [comment]
@MantasVaitkunas :+1:

**Pull request closed without merging**
