### PR TITLE
remove position from metadata-settings array

### PR DESCRIPTION
**Pull request by alfredbez**
As far as I can see, the `position` value is not used anywhere.

If this Pull Request is merged we need to adjust also http://oxidforge.org/en/extension-metadata-file.html#settings

### CODE REVIEW

**Comment by sebbbbauer** [comment]
Hi alfredbez,

correct me, if i understand it wrong: you want to remove the adding of the column 'oxpos' in the table 'oxconfigdisplay'. If we do this, the order of the module config entries will not work any longer properly. 

Try this:
go to [the database.sql](https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Setup/Sql/database.sql#L646) and change the oxpos of some entries, reset the shop and compare the order. I didn't found a direct usage of the 'oxconfigdisplay'.'oxpos' either, but there is hidden magic, using the 'oxpos' for ordering the admin module settings entries. 

Is this your wished change (Sorry, if i understood your intent wrong)?

**Comment by alfredbez** [comment]
I used [this module](https://github.com/OXID-eSales/oxideshop_ce/tree/master/tests/Acceptance/Frontend/testData/modules/test1) to test this.

I changed the settings-array like this:
```php

    'settings' => array(
        array('position' => 6, 'group' => 'settingsEmpty', 'name' => 'testEmptyBoolConfig',     'type' => 'bool',     'value' => 'false'),
        array('position' => 5, 'group' => 'settingsEmpty', 'name' => 'testEmptyStrConfig',      'type' => 'str',      'value' => ''),
        array('position' => 4, 'group' => 'settingsEmpty', 'name' => 'testEmptyArrConfig',      'type' => 'arr',      'value' => ''),
        array('position' => 3, 'group' => 'settingsEmpty', 'name' => 'testEmptyAArrConfig',     'type' => 'aarr',     'value' => ''),
        array('position' => 2, 'group' => 'settingsEmpty', 'name' => 'testEmptySelectConfig',   'type' => 'select',   'value' => '', 'constrains' => '0|1|2'),
        array('position' => 1, 'group' => 'settingsEmpty', 'name' => 'testEmptyPasswordConfig', 'type' => 'password', 'value' => ''),

        array('group' => 'settingsFilled', 'name' => 'testFilledBoolConfig',     'type' => 'bool',     'value' => 'true'),
        array('group' => 'settingsFilled', 'name' => 'testFilledStrConfig',      'type' => 'str',      'value' => 'testStr'),
        array('group' => 'settingsFilled', 'name' => 'testFilledArrConfig',      'type' => 'arr',      'value' => array('option1', 'option2')),
        array('group' => 'settingsFilled', 'name' => 'testFilledAArrConfig',     'type' => 'aarr',     'value' => array('key1' => 'option1', 'key2' => 'option2')),
        array('group' => 'settingsFilled', 'name' => 'testFilledSelectConfig',   'type' => 'select',   'value' => '2', 'constrains' => '0|1|2'),
        array('group' => 'settingsFilled', 'name' => 'testFilledPasswordConfig', 'type' => 'password', 'value' => 'testPassword'),
    )
```

```
mysql> SELECT * FROM oxconfigdisplay WHERE OXCFGMODULE='module:test1';
+----------------------------------+--------------+--------------------------+----------------+-----------------+-------+---------------------+
| OXID                             | OXCFGMODULE  | OXCFGVARNAME             | OXGROUPING     | OXVARCONSTRAINT | OXPOS | OXTIMESTAMP         |
+----------------------------------+--------------+--------------------------+----------------+-----------------+-------+---------------------+
| b6bb86005eb37d0786c72c015edafea4 | module:test1 | testEmptyAArrConfig      | settingsEmpty  |                 |     3 | 2016-08-04 14:02:29 |
| 937025a8ae0b3433004d3363dd108d2d | module:test1 | testEmptyArrConfig       | settingsEmpty  |                 |     4 | 2016-08-04 14:02:29 |
| 3f80ce90fbd5aaf4dda92d8ff28f7a8c | module:test1 | testEmptyBoolConfig      | settingsEmpty  |                 |     6 | 2016-08-04 14:02:29 |
| bd3c9d68209f919c30fe692b07026e4e | module:test1 | testEmptyPasswordConfig  | settingsEmpty  |                 |     1 | 2016-08-04 14:02:29 |
| 4fe3e8064fa73a49cb64be104f69fc08 | module:test1 | testEmptySelectConfig    | settingsEmpty  | 0|1|2           |     2 | 2016-08-04 14:02:29 |
| c589345ac11dcd37b8b5bfc0d73dfdfb | module:test1 | testEmptyStrConfig       | settingsEmpty  |                 |     5 | 2016-08-04 14:02:29 |
| 1323479f3fb11d05764d6bc2703bb4a6 | module:test1 | testFilledAArrConfig     | settingsFilled |                 |     1 | 2016-08-04 14:02:29 |
| 54c9ee1b2455e46ab6c395122967eb9d | module:test1 | testFilledArrConfig      | settingsFilled |                 |     1 | 2016-08-04 14:02:29 |
| 0dcb876d698545e9649753f23a4ba7bc | module:test1 | testFilledBoolConfig     | settingsFilled |                 |     1 | 2016-08-04 14:02:29 |
| 810c139ebadb33c41f20621821f7a011 | module:test1 | testFilledPasswordConfig | settingsFilled |                 |     1 | 2016-08-04 14:02:29 |
| 1013c6c30871979bbc3324cd079e3141 | module:test1 | testFilledSelectConfig   | settingsFilled | 0|1|2           |     1 | 2016-08-04 14:02:29 |
| f79998fc0f30d24970c0dfd742e5f0ae | module:test1 | testFilledStrConfig      | settingsFilled |                 |     1 | 2016-08-04 14:02:29 |
+----------------------------------+--------------+--------------------------+----------------+-----------------+-------+---------------------+
12 rows in set (0.00 sec)
```

bildschirmfoto vom 2016-08-04 14-04-23

Why is the `position` also used only in the `select` example?
```php
'settings' => array(
    array('group' => 'main', 'name' => 'dMaxPayPalDeliveryAmount', 'type' => 'str',      'value' => '30'),
    array('group' => 'main', 'name' => 'blPayPalLoggerEnabled',    'type' => 'bool',     'value' => 'false'),
    array('group' => 'main', 'name' => 'aAlwaysOpenCats',          'type' => 'arr',      'value' => array('Preis','Hersteller')),
    array('group' => 'main', 'name' => 'aFactfinderChannels',      'type' => 'aarr',     'value' => array('1' => 'de', '2' => 'en')),
    array('group' => 'main', 'name' => 'sConfigTest',              'type' => 'select',   'value' => '0', 'constraints' => '0|1|2|3', 'position' => 3 ),
    array('group' => 'main', 'name' => 'sPassword',                'type' => 'password', 'value' => 'changeMe') 
)
```

**Comment by keywan-ghadami-oxid** [comment]
I don't know why the position setting is only used in the selectbox example but it can be used on every setting. It is used to order the settings within the admin aera in the select in
https://github.com/OXID-eSales/oxideshop_ce/blob/29cd70ea6d55cda6159f082fba657c46df942a45/source/Application/Controller/Admin/ShopConfiguration.php#L224

**Comment by alfredbez** [comment]
@keywan-ghadami-oxid that works for Shop-Configuration (since you show a code example from that controller), but not for Module-Configuration.

Take a look at [this method](https://github.com/OXID-eSales/oxideshop_ce/blob/29cd70ea6d55cda6159f082fba657c46df942a45/source/Application/Controller/Admin/ModuleConfiguration.php#L106) and [this template](https://github.com/OXID-eSales/oxideshop_ce/blob/86b9f06a5235fc64687ca12a7b3d0f98e0b5a0e8/source/Application/views/admin/tpl/module_config.tpl#L43-L48)

---

Instead of removing `position` we could add this feature also to ModuleConfiguration  and document it better.

I'd like to refactor also ShopConfiguration@loadConfVars and ModuleConfiguration@_loadMetadataConfVars, but that will be another PR.

**Comment by keywan-ghadami-oxid** [comment]
Ok now i got it: that sorting for module configuration does not work, because ModuleConfiguration@_loadMetadataConfVars does not use the order from parent call ShopConfiguration@loadConfVars  right? Personally i would prefere to fix the module configuration to respect the order defined by 'posittion' instead of removing that feature.

**Comment by sebbbbauer** [comment]
Hi @all, 
i would prefer to make a bug entry (if there is no) and close this pull request. Than anybody can fix it, maybe in a new pull request :)

**Comment by alfredbez** [comment]
Right now the order is simply defined by the order of the settings array, because the settings are loaded from the metadata.php directly and not from the database. Is it better to load the settings from the database and order them by the oxpos-field or to use the current method and load it from the file sort them by their order in the settings array?
Loading them from the database makes refactoring and abstraction easier. I would suggest that we can Import them and set the position if it is not set by order from the array.

**Comment by keywan-ghadami-oxid** [comment]
@alfredbez +1 for loading from the database, +1 for using the order in the metadata for the position field on import.
But now i have to revert my statement from the comment before i think the support for the postion attribute in metadata.php can be droped because we can rely on the order defined in that file because else we would have conflicting functionality: order in which the settings listed in the metadata vs position.

**Comment by Sieg** [comment]
Thanks for your pull request, @alfredbez. In the mean time, I contacted the Product Owner for a decision and he clearly stated that he'd prefer a fix of this bug. You mentioned before that you're interested in refactoring this code snippet by yourself. Are you still up to it? ^^

**Comment by Sieg** [comment]
Hello @alfredbez, It been a while after our last comments on this question, and there is no further development of the topic, so I am closing this pull request for now. Consider reporting this problem as a bug in bugtrack (https://bugs.oxid-esales.com) if there is none registered yet. Please improve the solution as discussed above and reopen/create a new pull request if you are still interested in fixing this place. Thanks for your interest and contributions!

**Pull request closed without merging**
