### PR TITLE
add more support for namespaces in modules

### PR DESCRIPTION
**Pull request by revoltek-daniel**
add more support for namespaces in modules

### CODE REVIEW

**Comment by MantasVaitkunas** [comment]
Thanks @revoltek-daniel . I tried to use your code but miserably failed. Most likely I don't know how to use it properly. Could you please explain a bit deeper?

**Comment by revoltek-daniel** [comment]
@MantasVaitkunas if a module has a namespace like acme\module1\controllers\ClassName the _getInvalidExtensions method will try to look if this file exists, but because of the backslash the path is invalid even if the file exists.

In getIdByPath the moduleId is never found cause the module path will be acme/module1 but the $sModule Var will be acme\module1\controllers\ClassName so the module id at the end of this method will be "acme\module1\controllers\ClassName" and this is incorrect.

**Comment by oxidsupport** [comment]
Is this pull request related to https://bugs.oxid-esales.com/view.php?id=6228 or https://bugs.oxid-esales.com/view.php?id=5916 or #178 ?

**Comment by revoltek-daniel** [comment]
@oxidsupport not directly, it's a general "bug" if you use modules with namespaces to extend oxid classes.

**Comment by MantasVaitkunas** [comment]
Hi again, and sorry for delay.
So I'm trying to check if it works. I added namespace for demo module class: https://github.com/MantasVaitkunas/loggerdemo/commit/04603050c52d62c254699337e2d473624194f37f

In this case when i turn on home page I get class not found exception. Error log shows: "Faulty component --> oxbasket". So what I'm doing wrong?

**Comment by revoltek-daniel** [comment]
@MantasVaitkunas did you modiffy your metadata file?
I will try your example modul next weekend.

**Comment by MantasVaitkunas** [comment]
Well, I tried lots of variations :)

**Comment by Shiftas** [comment]
@revoltek-daniel, I also really tried to get it running but can't even see how it should work. Anyways, we will introduce name spaces with one of the upcoming versions of OXID eShop but have some differnt implementation in mind than you came up with. You mind us skipping your pull request this time?

**Comment by revoltek-daniel** [comment]
Hallo @Shiftas, this is no fix to add namespace Support to Oxid.  This is an improvement if namespaces are working (Use classmap Feature of composer autoloader)

**Comment by Shiftas** [comment]
Hello @revoltek-daniel,
we are going to refactor the entire piece of implementation so I am not really sure if your PR will still be helpful after this refactoring is done. Would you mind us to skip your pull request this time - maybe it is more useful to re-send it after the refactoring is done.

**Comment by MantasVaitkunas** [comment]
Going to close it. Please see notes by @Shiftas before.

**Pull request closed without merging**
