### PR TITLE
Language abbreviation with underscore

### PR DESCRIPTION
**Pull request by preethi-sivasankaran**
The Language abbreviation that was saved with a '-' gets replaced with '_' when URI is created. But the comparison made in oxseoencoder.php, compares the uri with the Language abbreviation from the database. Hence do not match. And so repeatedly added to the URI for Languages with abbreviation using an Underscore.

### CODE REVIEW

**Comment by sebbbbauer** [comment]
Hi Preethi,
cool, that you found that and fixed it. Could you please add a test, which covers this one? We have several unit/integrations tests for the seo things - it seems possible, that there is one, which covers nearest code.

I label this one bug, cause it seems like a bug, even there is no bug for this in the tracker.

**Comment by keywan-ghadami-oxid** [comment]
https://bugs.oxid-esales.com/view.php?id=6407

**Comment by preethi-sivasankaran** [comment]
@sebbbbauer 
Hi Sebastian,
I've added the unit test corresponding to the bugfix. 
Thanks.

**Comment by sebbbbauer** [comment]
Already merged

**Pull request closed without merging**
