### PR TITLE
Add manufacturer breadcrumb

### PR DESCRIPTION
**Pull request by Sioweb**
What is it:

1. Open manufacturer
2. Choose Product
3. No Breadcrump appears

Thats because ArticleDetailsController.php has no case for manufacturer products details - like it has for vendor.

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @Sioweb, i have opened the manufacturer, than going to product and i see some breadcrumbs. Can you tell me more how to reproduce your issue?

image

**Comment by Sioweb** [comment]
Ja stimmt, das Problem liegt nicht in Oxid. Wir nutzen das Modul `Search XL`, es überschreibt die Locator-Methode `_setManufacturerLocatorData`, die verhindert dass die Breadcrumb geladen wird, wenn ein Modulconfig-Parameter gesetzt wird.

Ich denke dann ist der PR hinfällig, mir kam es nur seltsam vor, dass Vendor in der Methode `getBreadCrumb` extra eingetragen ist und Manufacturer nicht.

LG
Sascha

**Comment by keywan-ghadami-oxid** [comment]
@sieg it was confirmed by the author of this PR that you are right and this can be closed(issue was caused by a module). Anyway he is wondering why at this place vendor is explcetly but not manufacturer.

**Comment by Sieg** [comment]
Hello guys, So, why vendor dont have condition? - Probably because it can work with the same code as category works :) And if it fits, why to make it more complex?

Thanks for fast response, closing the PR.

**Pull request closed without merging**
