### PR TITLE
As a community developer, I want to be sure, that the OXID-eShop tests are functional in the oxvm_eshop enviroment

### PR DESCRIPTION
**Pull request by patrick-blom**
### Scenario  /  Steps to reproduce
- fire up the [oxvm_eshop](https://github.com/OXID-eSales/oxvm_eshop) 
- navigate to /var/www/oxideshop
- run the command `php vendor/bin/runtests`

### Accepted
- The build in test will pass with no error

### Current
- The tests will crash with the following error message
`Adding unit tests from /var/www/oxideshop/tests/Unit/Core/Module/*Test\.php
Adding unit tests from /var/www/oxideshop/tests/Unit/Core/Service/*Test\.php
Adding unit tests from /var/www/oxideshop/tests/Unit/Core/Smarty/*Test\.php
PHP Warning:  require_once(/var/www/oxideshop/tests/Unit/Core/Smarty/../../../../source/Core/Smarty/Plugin/prefilter.oxblock.php): failed to open stream: No such file or directory in /var/www/oxideshop/tests/Unit/Core/Smarty/PluginSmartyOxBlockTest.php on line 17
PHP Stack trace:
PHP   1. {main}() /var/www/oxideshop/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /var/www/oxideshop/vendor/phpunit/phpunit/phpunit:47
PHP   3. PHPUnit_TextUI_Command->run() /var/www/oxideshop/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->getTest() /var/www/oxideshop/vendor/phpunit/phpunit/src/TextUI/Command.php:122
PHP   5. ReflectionMethod->invoke() /var/www/oxideshop/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
PHP   6. AllTestsRunner::suite() /var/www/oxideshop/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
PHP   7. AllTestsRunner::_addFilesToSuite() /var/www/oxideshop/vendor/oxid-esales/testing-library/AllTestsRunner.php:54
PHP   8. PHPUnit_Framework_TestSuite->addTestFile() /var/www/oxideshop/vendor/oxid-esales/testing-library/AllTestsRunner.php:142
PHP   9. PHPUnit_Util_Fileloader::checkAndLoad() /var/www/oxideshop/vendor/phpunit/phpunit/src/Framework/TestSuite.php:335
PHP  10. PHPUnit_Util_Fileloader::load() /var/www/oxideshop/vendor/phpunit/phpunit/src/Util/Fileloader.php:38
PHP  11. include_once() /var/www/oxideshop/vendor/phpunit/phpunit/src/Util/Fileloader.php:56
PHP Fatal error:  require_once(): Failed opening required '/var/www/oxideshop/tests/Unit/Core/Smarty/../../../../source/Core/Smarty/Plugin/prefilter.oxblock.php' (include_path='/var/www/oxideshop/vendor/symfony/yaml:.:/usr/share/php') in /var/www/oxideshop/tests/Unit/Core/Smarty/PluginSmartyOxBlockTest.php on line 17
PHP Stack trace:
PHP   1. {main}() /var/www/oxideshop/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /var/www/oxideshop/vendor/phpunit/phpunit/phpunit:47
PHP   3. PHPUnit_TextUI_Command->run() /var/www/oxideshop/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->getTest() /var/www/oxideshop/vendor/phpunit/phpunit/src/TextUI/Command.php:122
PHP   5. ReflectionMethod->invoke() /var/www/oxideshop/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
PHP   6. AllTestsRunner::suite() /var/www/oxideshop/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
PHP   7. AllTestsRunner::_addFilesToSuite() /var/www/oxideshop/vendor/oxid-esales/testing-library/AllTestsRunner.php:54
PHP   8. PHPUnit_Framework_TestSuite->addTestFile() /var/www/oxideshop/vendor/oxid-esales/testing-library/AllTestsRunner.php:142
PHP   9. PHPUnit_Util_Fileloader::checkAndLoad() /var/www/oxideshop/vendor/phpunit/phpunit/src/Framework/TestSuite.php:335
PHP  10. PHPUnit_Util_Fileloader::load() /var/www/oxideshop/vendor/phpunit/phpunit/src/Util/Fileloader.php:38
PHP  11. include_once() /var/www/oxideshop/vendor/phpunit/phpunit/src/Util/Fileloader.php:56
Uncaught exception. See error log for more information.`

### Solution
- fix the path for the core directory in an  [oxvm_eshop](https://github.com/OXID-eSales/oxvm_eshop)  environment.

### Technical details
 - oxvm_eshop b-6.1
 - oxideshop-metapackage-ce v6.1.2
 - oxid eshop_ce reference [05b11e27abb4d6fd894ef2d0c983569be2f198ad](https://github.com/OXID-eSales/oxideshop_ce/commit/05b11e27abb4d6fd894ef2d0c983569be2f198ad)

### Commit Message
- add different require_once path for smarty tests, to make them functional in the official oxvm_eshop environment

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
@patrick-blohm for my personal interest I am wondering if the old path can simply be replaced, as it is not related to the oxvm filestructure which is simlar to other environments where the source files are within the vendor folder, or not?

**Comment by patrick-blom** [comment]
> @patrick-blom for my personal interest I am wondering if the old path can simply be replaced, as it is not related to the oxvm filestructure which is simlar to other environments where the source files are within the vendor folder, or not?

Hey @keywan-ghadami, i hope i got your question right. The complete source files are located in the vendor folder which is filled by composer. On the same level there is the document root source folder, which is used as the entry point for apache and in this case for the tests. But the problem is that the document root source folder does not contain the Core directory which is placed in the composer vendor directory. 

For the other tests, this is no problem because they use normal namespaces. So the psr autoloader will take care of the requiring. But the files I changed handle the requirement by them selfs. So they try to require the smarty functions/methods/modifiers form the document root source directory which does not contain the Core directory which simply causes the error.

**Comment by keywan-ghadami-oxid** [comment]
@patrick-blom thank you that is perfectly clear to me, it's just about if your fix can be simplified by removing the check for the old file structure e.g.
https://github.com/OXID-eSales/oxideshop_ce/pull/682/files#diff-3b52b5d2a09de94f4fee05148b85d3dcR17
I think that is safe to remove, but maybe I miss something.

**Comment by patrick-blom** [comment]
@keywan-ghadami ah sorry, now it's 100% clear to me. Yes, this can be simplified if, the path is no longer in use.

I created a second pull request with a simplified version of the fix. Feel free  to test it in detail =)  
 [PR 684](https://github.com/OXID-eSales/oxideshop_ce/pull/684)

**Pull request closed without merging**
