### PR TITLE
Adding monolog as the default logger to OXID

### PR DESCRIPTION
**Pull request by flow-control**
There are really awesome libraries for application logging in PHP, and as OXID does not use one of them, i thought it's about time. I stopped reworking everything logging at the `OxidEsales\EshopCommunity\Core\Exception` Class, as i saw the deprecated notices everywhere. If you like, i can rewrite that part as well and remove the deprecated methods. I think with the upcoming release of 6.0, it is a good point in time to remove the methods marked for deprecation in OXID version 5.3. But this could also be done in another pull request

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
@flow-control I also love to see built a built in logger support.  Thank you for your pull requestest. One idea to improve your code: the core Logger class is not needed, it is substituted with monolog anyway, and would need a loggerimpl. to be functional.

**Comment by flow-control** [comment]
I feel the same way about that core logger class, but it's done in a similar way as the database layer. Someone told me that this is done in case you ever ditch doctrine. If we agree on the psr3 interface, than of course this argument back than would be invalid. So you are right, I will remove it. What's your opinion on the exception classes, should I refactor those to use the new logger, or should that be kept open for another or?

**Comment by keywan-ghadami-oxid** [comment]
@flow-control that is very difficult question for me, I did similar pull request in the past with monolog configuration file and configurable exception handler, dependency injection and unittests and it grown to big for me to maintain it over a long a time while core team was refactoring for version 6.
https://github.com/OXID-eSales/oxideshop_ce/pull/437/ and another back in 2015 (that was also conflicting with namespace impl.)
I still would like to have all the features, but that would also increase the effort and maybe discussion and so the duration until the logger finds it's way to the core. 
So my suggestion is for you and the the core team to try a very basic(mvp) in the first step. 
But feel free to decide on your self, you can also take code from my pull request into yours (no need to mention my name by doing so).

**Comment by flow-control** [comment]
rebased on current master

**Comment by proudcommerce** [comment]
+1

**Comment by mattvb91** [comment]
+1

**Comment by tmloberon** [comment]
+1

**Comment by flow-control** [comment]
any news on this?

**Comment by SchramlTim** [comment]
+1

**Comment by Sieg** [comment]
Hi @flow-control, the discussion about your pull request is in progress. What you could do for now - please check the failing test.

**Comment by mattvb91** [comment]
@Sieg any update on this?

**Comment by Sieg** [comment]
Hello guys, some update: core team has a story for integrating the PSR logger, and the pull request is linked there.

**Comment by gregorhyneck** [comment]
As already mentioned by @Sieg, the core team will merge your pull request soon. Thank you for that! We decided to have some things on top  (everyting fine with your pull request):
- log level configurable
- wrapper for monolog in order to use only the methods defined in Psr\Log\LoggerInterface
The core team will implement those changes soon.

**Comment by Sieg** [comment]
Hello guys! Thanks for the contribution. As you have probably already noticed, the core team have implemented some more changes on the top of this pull request, and it is merged to b-6.x and master recently!

**Pull request closed without merging**
