### PR TITLE
Fixed some phpcs errors

### PR DESCRIPTION
**Pull request by alfredbez**
This PR contains several commit which fixes some phpcs errors. -Feel free to cherry pick single commits, if the whole PR is not atomic enough.- I created seperate PRs for every change now.

---

I'll try to explain every commit and what I changed there:

**rename $SMTP_PORT to $smtpPort** - [show](eeca5433712882ad0e4cb5e27b9d6736b83fd42f) -> #563
This is a property in the `Email` class, which extends the `PHPMailer` class (class.phpmailer.php).
The property `SMTP_PORT` is used only in the `SMTP` class (class.smtp.php)
```
$ grep -rI 'SMTP_PORT' .
./vendor/phpmailer/phpmailer/class.smtp.php:    const DEFAULT_SMTP_PORT = 25;
./vendor/phpmailer/phpmailer/class.smtp.php:     * @deprecated This is only ever used as a default value, so use the `DEFAULT_SMTP_PORT` constant instead
./vendor/phpmailer/phpmailer/class.smtp.php:     * @see SMTP::DEFAULT_SMTP_PORT
./vendor/phpmailer/phpmailer/class.smtp.php:    public $SMTP_PORT = 25;
./vendor/phpmailer/phpmailer/class.smtp.php:            $port = self::DEFAULT_SMTP_PORT;
```

---

**ignore StrMb-wrapper functions (phpcs)** - [show](39964a6bee978430480734e25163a5a5160011b3) -> #566
The `StrMb` Class wraps some php functions like `preg_match`. Some of these functions are not in camelCase. phpcs reports this as an error, so I wrapped that in an ignore block (via `@codingStandardsIgnoreStart` and `@codingStandardsIgnoreEnd`)

---

**changed Hasher from abstract class to interface** - [show](fe77cffe4adb221cc025124f7be2640321d7b8c6) -> #564
phpcs reported that Hasher@hash declares a return type in the DocBlock without returning anything. The `hash` method is actually an `abstract` method and contains no code. I think it is cleaner to use an interface here.
I'm not sure how to deal with that `BackwardsCompatibilityClassMap` array, see this line:
```
'OxidEsales\\Eshop\\Core\\Hasher' => 'oxhasher',
```

---

**apply PSR-2 style rules to Sha512Hasher.php** - [show](f47967efbca0e5840524d6833770c24fb0526dcf) -> #565
I replaced `$sString` with `$string`.

### CODE REVIEW

**Comment by alfredbez** [comment]
The PHP-7.0 Build Job failed
```
Err http://downloads-distro.mongodb.org dist/10gen Translation-en_US
  Unable to connect to downloads-distro.mongodb.org:http:
Err http://downloads-distro.mongodb.org dist/10gen Translation-en
  Unable to connect to downloads-distro.mongodb.org:http:
W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/i18n/Translation-en_US  Unable to connect to downloads-distro.mongodb.org:http:

W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/i18n/Translation-en  Unable to connect to downloads-distro.mongodb.org:http:

E: Some index files failed to download. They have been ignored, or old ones used instead.


The command "sudo apt-get update" failed and exited with 100 during .

Your build has been stopped.
```

I'll close and reopen this PR to trigger a new build.

**Comment by keywan-ghadami-oxid** [comment]
Hi Alfred,  if you like you can also rebase & edit some commits and force push the feature branch to trigger rebuild.

**Comment by alfredbez** [comment]
I think it works now. The build was not finished when I closed & reopened.

**Comment by alfredbez** [comment]
I created seperate PRs for every commit:

**rename $SMTP_PORT to $smtpPort** - #563
**ignore StrMb-wrapper functions (phpcs)** - #566
**changed Hasher from abstract class to interface** - #564
**apply PSR-2 style rules to Sha512Hasher.php** - #565

I close this one now.

**Pull request closed without merging**
