### PR TITLE
fixed wrong and misleading translation of "role"

### PR DESCRIPTION
**Pull request by SvenBrunk**
"role" is not "Recht", but "Rolle". Recht == right or permission

### CODE REVIEW

**Comment by MantasVaitkunas** [comment]
@SvenBrunk, thanks for your pull request. Unfortunately, something went terribly wrong as we see 408 changes in this file, think you originally wanted to change just some stuff. Can you please try to send another commit with just your changes? 
Also, as you can see, the tests didn't run through properly: https://travis-ci.org/OXID-eSales/oxideshop_ce/jobs/63161975. This is most likely because you changed the encoding. Please check this as well. Cheers!

**Comment by SvenBrunk** [comment]
Hi Mantas,

you are right, I only changed 3 lines or so...
I did this using the github edit function that more or directly creates a pull request.

So I guess you should also check the configuration on your side :)

I will repeat this again by checking it out to my machine.

Kind regards,
Sven


Von: Mantas Vaitkūnas [mailto:notifications@github.com]
Gesendet: Dienstag, 26. Mai 2015 14:18
An: OXID-eSales/oxideshop_ce
Cc: Sven Brunk
Betreff: Re: [oxideshop_ce] fixed wrong and misleading translation of "role" (#235)


@SvenBrunk<https://github.com/SvenBrunk>, thanks for your pull request. Unfortunately, something went terribly wrong as we see 408 changes in this file, think you originally wanted to change just some stuff. Can you please try to send another commit with just your changes?
Also, as you can see, the tests didn't run through properly: https://travis-ci.org/OXID-eSales/oxideshop_ce/jobs/63161975. This is most likely because you changed the encoding. Please check this as well. Cheers!

**Comment by SvenBrunk** [comment]
Interesting... github frontend still shows only 1 difference... as it should be, but travis shows wrong encoded characters for some tests

**Comment by SvenBrunk** [comment]
I make a fresh pull request. Might be it also based on my own old copy/fork of this

**Pull request closed without merging**
