### PR TITLE
performance and encodings

### PR DESCRIPTION
**Pull request by keywan-ghadami-oxid**
performance improfements for utf8 mode

- do not convert utf8 encoding if already utf8
- in function _recodeLangArray
  -  removed statements without effects unset($aLangArray[$sKey]);
  -  removed second variable for array keys
- convert languange files to utf8
- change unittest to be able to detect utf8 encoding

bug fix:
 - encode utf8 to baseLang if not utf mode
 - changed unittest for that
 - change unit tests to give correct error message

### CODE REVIEW

**Comment by Shiftas** [comment]
@keywan-ghadami, unfortunately we cannot merge your pull request as nearly at the same time we were working on the same issue, see this:
https://github.com/OXID-eSales/oxideshop_ce/commit/fd6f97b6fce54655ee262d6361618d939202b273

**Comment by keywan-ghadami-oxid** [comment]
as i remember this pull request was rebased so that it only contains further improvements that are not in fd6f97b, please double check if not loosing some improvements by closing this.

**Comment by keywan-ghadami-oxid** [comment]
rebased again ready for review ;-)

**Comment by Sieg** [comment]
Thanks @keywan-ghadami-oxid, I have merged your pull request. Please, be careful with BOM in php files.

**Pull request closed without merging**
