### PR TITLE
Alternative to DbMetaDataHandler::fieldExists() or tableExists() a other concept

### PR DESCRIPTION
**Pull request by TumTum**
Sometimes the event 'onActivate' is used, when a module is activated. To adjust the database tables. For this purpose the DbMetaDataHandler class was used to adjust the tables.

My idea would be to use a library. That does a check of the database structure and automatically adds the columns or creates the whole table if it doesn't exist.

The developer writes exactly what he needs and the rest does the framework.

Example:

> module/my/metadata.php

```php
'events' => [
      'onActivate'   => 'my\\ModuleInit::onActivate',
      'onDeactivate' => 'my\\ModuleInit::onDeactivate'
  ],
```

> module/my/myModuleInit.php

```php
namespace my;

use OxidEsales\EshopCommunity\Internal\Framework\Module\Setup\Template\ModuleEventsInterface;
use tm\oxid\SchemaExpander\DesireExpander;

class ModuleInit implements ModuleEventsInterface
{
    /**
     * What is new: the onActivate function was given the library as parameter.
     * Which takes care that the table looks like it was described.
     *
     * @param DesireExpander $desireExpander
     */
    public function onActivate(DesireExpander $desireExpander)
    {
        // Simple create new table
        $desireExpander
            ->table('tm_example')
                ->addFieldOxid()
                ->addFieldOxactive()
                ->addFieldOxactiveFrom()
                ->addFieldOxactiveTo()
                ->addField('OXHASH', "char(32) COLLATE latin1_general_ci NOT NULL DEFAULT '' COMMENT 'Hash'")
                ->addField('OXTIME', "int(11) NOT NULL COMMENT 'Validation time'")
                ->addFieldOxtimestamp()
                ->setPrimaryKey('OXID');

        // Extent a oxarticles table
        $desireExpander
            ->table('oxarticles')
                ->addField('MYCOLUMN', "char(32) NOT NULL DEFAULT 'Wowo' COMMENT 'Extent only one Column'")
                ->after('oxlang');
    }

    public static function onDeactivate()
    {
    }
}
```

If you like that idea, I can write the appropriate tests.

### CODE REVIEW

**Comment by Sioweb** [comment]
Using a shema builder, is a great idea.

Oxid use doctrine to do migrations, maybe we should also think about using its querybuilder, or entities in some future. It has a lot of modular features and a big community.

**Comment by alfredbez** [comment]
Not directly related, but we still need some way to change the database structure for already active modules. Maybe the `onActivate` event should not contain the schema changes itself, but only trigger them. Additionally, we need a way to trigger them for already active modules, e.g. with the migration-command.

---

Just an idea: Put this migration / schema-definition in a file (e.g. `schema.php`, `migration.php`, `database.php`, etc.) and make it a default `onActivate` event.

Example:
1. We have a module with a `schema.php` (contains DesireExpander / migrations)
2. If you activate the module, the shop detects the `schema.php` during the shop-default `onActivate` event (without the need to the `'onActivate'   => 'my\\ModuleInit::onActivate'` entry in the `metadata.php`)
3. Something in the module changed and we need an additional field or table
4. You adapt the `schema.php`
5. During the deployment, the command `oe-eshop-db_migrate` will execute the `schema.php` for all active modules
6. You have the changed schema, no need to deactivate and re-activate the module

**Comment by Sioweb** [comment]
Thats also possible with Doctrine, u just add the wantet shema and docrine will check em all and build it with - for example - the comand line: `vendor/bin/console doctrine:schema:update -f`

**Comment by IgorIe** [comment]
You don't need to use onActivation at all, there is FinalizingModuleActivationEvent, you can register a subscriber in your module and do whatever you want on this event, use any third party libraries. You already have access to the doctrine query builder via service QueryBuilderFactoryInterface, just inject it in your subscriber and use it.

We have also plans to implement migrations (maybe doctrine migrations) for modules, what should fix the problem.

**Comment by TumTum** [comment]
It doesn't matter if you use common third party libraries to handle the DB communication. However, standardized columns such as OXID, OXACTIVEFROM, OXTIMESTAMP, and so on should be easy to call using a function. Not that everyone tinkers like his own SQL.

@alfredbez in your method. I've made sure the module can't work unless the schematic is changed. With the automatic activation, the DB is finished and the module is active. You don't have to go back in through the CLI and process it again.

@Sioweb ContainerFactory::getInstance()->getContainer()->get(QueryBuilderFactoryInterface::class)->create() Then you already have your QueryBuilder.

**Comment by Sieg** [comment]
Hello guys. Thanks for your input in improving the installation process of the modules.

For now, as Igor already mentioned, there are a couple of ways how you can do suggested things for your projects - please use them. Later on, with improving the migrations system to support module migrations, everything suggested here, will be done much simpler as well, and this was mentioned by Igor too.

**Comment by TumTum** [comment]
Okay. I will wait to see what's going to happen.

**Pull request closed without merging**
