### PR TITLE
Cleanup and deprecated all $this->getConfig() calls

### PR DESCRIPTION
**Pull request by flow-control**
This merge request:

- deprecates all `getConfig()` methods beside the one in the `OxidEsales\Eshop\Core\Registry` (for obvious reasons) and the one in `OxidEsales\Eshop\Core\ViewConfig` because it may be used in templates
- changes all calls to `$this->getConfig()` to `OxidEsales\Eshop\Core\Registry::getConfig()`

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @flow-control, thanks for your interest in improving the code!

A little problem I spot here - we could deprecate these methods in b-6.x already, and thats preferable way, as if we will do it in master, the method itself can be removed in OXID 8.0 only, and thats now what we want ;)

Furthers, even if we will do the deprecation, we will not remove the method itself Right now, as part of the modules will break, as they are using that view method for sure, but, we will clean up there with some time and remove those methods in master.

So, would you be interested in rebasing this PR on our b-6.x branch? ;)

**Comment by flow-control** [comment]
Hey @Sieg,

sounds good, i rebased on branch `b-6.x` and updated the pull request accordingly.

Let me know if you have any questions.

/Flo

**Comment by Sieg** [comment]
Hey @flow-control, i have done some fixes after reviewing the changes.. But some of the tests are still failing, and the reason is using of fakeModuleStructure() method which changes the path of the shop source to virtual one. If you have some time to investigate it - please, do so.

**Comment by Sieg** [comment]
Hey @flow-control, i forgot to mention - please take pr721 branch with my fixes :)

**Comment by flow-control** [comment]
Hey @Sieg,

i fixed the build in `pr721` branch

/Flo

**Comment by Sieg** [comment]
Hello @flow-control, have just merged the changes at https://github.com/OXID-eSales/oxideshop_ce/commit/0add584305c74b2110a5eeb1d3a42dfb16825ede. Have a nice evening.

**Pull request closed without merging**
