### PR TITLE
Added alternate-hreflang-Link-Element in head

### PR DESCRIPTION
**Pull request by Crease29**

### CODE REVIEW

**Comment by Crease29** [comment]
More information about this topic: https://support.google.com/webmasters/answer/189077?hl=en

**Comment by suabo** [comment]
:+1:

**Comment by suabo** [comment]
:+1:

**Comment by ooxi** [comment]
:+1:

**Comment by tabsl** [comment]
i also would add "x-default" ...

**Comment by Crease29** [comment]
Done: cd74ec02669e6e0dcff0e562e0da49f40516c0d1

**Comment by MantasVaitkunas** [comment]
Hi @Crease29. Thanks for contribution. Waiting for PO decision.

**Comment by MantasVaitkunas** [comment]
@Crease29, thanks for you pull request once again. The idea of this feature is absolutely right and valuable, alone the implementation could be optimized in my opinion.
On the one hand, all of the logic like URL forming shall go to PHP classes. Proper usage could look in this example: 
```smarty
   [{block name="head_link_hreflang"}]
        [{if $oView->isLanguageLoaded()}]
            [{foreach from=$oView->getLanguages() item=language}]
                <link rel="alternate" hreflang="[{$language->abbr}]" href="[{$language->link}]"/>
            [{/foreach}]
        [{/if}]
    [{/block}]
```
Also, I'd suggest to think about the string replace in your code. Better to not hard code the URL and to make it language dependent.
 
As agreed in PM, we are going to close this PR. Cheers!

**Pull request closed without merging**
